# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports: 
      - 5432:5432
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 10000:8080
  zuul-gateway:
    container_name: zuul-gateway
    image: zuul-gateway
    ports:
      - 8080:8080
    links:
      - movies-microservice:movies-microservice
      - eureka-server:eureka-server
  movies-microservice:
    container_name: movies-microservice
    image: movies-microservice
    ports:
      - 8081:8081
    links:
      - eureka-server:eureka-server
  eureka-server:
    container_name: eureka-server
    image: eureka-server
    ports:
      - 8761:8761