# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports: 
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080
  zuul-gateway:
    image: zuul-gateway
    ports:
      - 8080:8080
    links:
      - movie-microservice:movie-microservice
      - eureka-server:eureka-server
  movie-microservice:
    image: movie-microservice
    ports:
      - 8081:8081
    links:
      - eureka-server:eureka-server
  eureka-server:
    image: eureka-server
    ports:
      - 8761:8761