server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
      
ribbon:
  eureka:
    enabled: false
    
zuul:
  routes:
    movies:
      path: /movies/**
      url: http://192.168.99.100:8081/movies
    actors:
      path: /actors/**
      url: http://192.168.99.100:8081/actors
  
spring:  application:    name: zuul-gateway