server:
  port: 8080

eureka:
  instance:    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      
ribbon:
  eureka:
    enabled: true
    
zuul:
  routes:
    movies:
      path: /movies/**
      serviceId: movies-microservice
    actors:
      path: /actors/**
      serviceId: movies-microservice
      
spring:  application:    name: zuul-gateway